version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:942605225521:task-definition/pod-3-return-order-comp-process-td:1"
        LoadBalancerInfo:
          ContainerName: "mfpe-aws-component-processing-module"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"
